"""create base tables

Revision ID: ff9e9ea3f721
Revises: 3b4c5d6e7f8g
Create Date: 2026-01-25 21:59:48.296725

"""
from alembic import op
import sqlalchemy as sa


revision = 'ff9e9ea3f721'
down_revision = '3b4c5d6e7f8g'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('unified_social_credit_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.Enum('PERSON', 'COMPANY', name='doc_scope_enum'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'code', name='uniq_scope_code')
    )
    op.create_index('idx_doc_types_scope', 'document_types', ['scope'], unique=False)
    op.create_index('idx_document_types_code', 'document_types', ['code'], unique=False)
    op.create_index('idx_document_types_name', 'document_types', ['name'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('ext', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id_number', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_name'), 'persons', ['name'], unique=False)
    op.create_table('stored_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('ext', sa.String(length=10), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_rel_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', name='uniq_sha256')
    )
    op.create_index('idx_stored_files_created_at', 'stored_files', ['created_at'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.Enum('PERSON', 'COMPANY', name='evidence_scope_enum'), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('cert_no', sa.String(length=128), nullable=True),
    sa.Column('issuer', sa.String(length=256), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'EXPIRED', 'UNKNOWN', name='evidence_status_enum'), server_default='UNKNOWN', nullable=False),
    sa.Column('tags', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['stored_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cert_no', 'evidences', ['cert_no'], unique=False)
    op.create_index('idx_expires_at', 'evidences', ['expires_at'], unique=False)
    op.create_index('idx_issuer', 'evidences', ['issuer'], unique=False)
    op.create_index('idx_scope_doc', 'evidences', ['scope', 'document_type_id'], unique=False)
    op.create_index('idx_scope_owner', 'evidences', ['scope', 'owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scope_owner', table_name='evidences')
    op.drop_index('idx_scope_doc', table_name='evidences')
    op.drop_index('idx_issuer', table_name='evidences')
    op.drop_index('idx_expires_at', table_name='evidences')
    op.drop_index('idx_cert_no', table_name='evidences')
    op.drop_table('evidences')
    op.drop_index('idx_stored_files_created_at', table_name='stored_files')
    op.drop_table('stored_files')
    op.drop_index(op.f('ix_persons_name'), table_name='persons')
    op.drop_table('persons')
    op.drop_table('files')
    op.drop_index('idx_document_types_name', table_name='document_types')
    op.drop_index('idx_document_types_code', table_name='document_types')
    op.drop_index('idx_doc_types_scope', table_name='document_types')
    op.drop_table('document_types')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
